### ISSUE TITLE
CodeReady Studio Does Not Prompt Workspace Selection

### ISSUE THREAD

**Issue by PStoner3** [jbdevstudio/jbdevstudio-product#572]
CodeReady Studio Version: 12.19.1.GA

Scenario: When starting up CRS, it does not prompt me to select a workspace, it simply opens to a default workspace. The startup process seems to ignore the "Prompt for workspace on startup" setting. Once the IDE starts up, I have to then switch workspaces in order to get to my desired code base.

Expected result: CRS would honor the setting General > Startup and Shutdown > Workspaces > "Prompt for workspace on startup" and I would be presented with a dialog from which to select my workspace.

**Comment by jeffmaury** [comment]
I can't reproduce. Which OS are you on ?

**Comment by PStoner3** [comment]
Windows 10 version 2004 OS Build 19041.1110.

I installed using the codereadystudio-12.19.1.GA-installer-standalone.jar

**Comment by PStoner3** [comment]
Some additional information. I just realized CRS opens to _C:\Users\_username_\workspace by default. If I delete this folder and open CRS again, this folder is recreated and used as the default. My preferences are set as shown in the attached screenshot.

![CRS_WS_Preferences](https://user-images.githubusercontent.com/17929362/130091621-5e66d39d-4a66-4f4a-8602-2ccb92a35aef.png)

**Comment by jeffmaury** [comment]
How do you launch CRS ?

**Comment by PStoner3** [comment]
Launch using C:\Users\*****\codeready\codereadystudio\studio\codereadystudio.exe

**Comment by jeffmaury** [comment]
Can't reproduce. Which Java VM is running CRS ?

**Comment by PStoner3** [comment]
@jeffmaury Your question got me to thinking. I opened the readme and found the section "**Selecting a workspace**". The last line of this section reads "For shared or multi-workspace installs you must explicitly specify the location for your workspace using the dialog (or via the " -data " command line argument)."

Since I am not presented with the workspace dialog I tried `C:\Users*****\codeready\codereadystudio\studio\codereadystudio.exe -data` and `C:\Users\*****\codeready\codereadystudio\studio\codereadystudio.exe - data C:\Users\*****\development\code\microservices\pm`.

Both were ignored and CRS opened to the default workspace.

**Comment by jeffmaury** [comment]
I don't get why I can't reproduce on my system. Any log that you could share ?

**Comment by PStoner3** [comment]
@jeffmaury openJDK11.

If I may ask. Did you use the installer jar to install? For regular Eclipse I download the zip file and extract the contents where I want them. Is there a zip archive for CRS?

**Comment by jeffmaury** [comment]
No I followed the installer.

**Comment by PStoner3** [comment]
See attached log file from recent start up.

The only thing that stands out, aside from the the failed attempts to retrieve TestNG repo content is the `Received fatal alert` message on line 21
[crs.log](https://github.com/jbdevstudio/jbdevstudio-product/files/7022112/crs.log)

**Comment by PStoner3** [comment]
Ok disregard. The SSL error was due to my lack of not setting my NTLM proxy inside CRS, like I do for Eclipse. That has been resolved. Now the log is clean

**Comment by jeffmaury** [comment]
Can you look at $CRS_FOLDER/studio/configuration/.settings/org.eclipse.ui.ide.prefs ?

**Comment by PStoner3** [comment]
Here are the content
```
MAX_RECENT_WORKSPACES=10
RECENT_WORKSPACES=C\:\\Users\\aa99988\\development\\code\\web\\java\nC\:\\Users\\aa99988\\development\\code\\microservices\\pm\nC\:\\Users\\aa99988\\development\\code\\java\nC\:\\Users\\aa99988\\development\\code\\quarkus\nC\:\\Users\\aa99988\\development\\code\\microservices\\messaging
RECENT_WORKSPACES_PROTOCOL=3
SHOW_RECENT_WORKSPACES=false
SHOW_WORKSPACE_SELECTION_DIALOG=false
eclipse.preferences.version=1
```

I'm going to change those two boolean parameters to true and see what happens

**Comment by PStoner3** [comment]
org.eclipse.ui.ide.perfs after change:
```
MAX_RECENT_WORKSPACES=10
RECENT_WORKSPACES=C\:\\Users\\aa99988\\development\\code\\web\\java\nC\:\\Users\\aa99988\\development\\code\\microservices\\pm\nC\:\\Users\\aa99988\\development\\code\\java\nC\:\\Users\\aa99988\\development\\code\\quarkus\nC\:\\Users\\aa99988\\development\\code\\microservices\\messaging
RECENT_WORKSPACES_PROTOCOL=3
SHOW_RECENT_WORKSPACES=true
SHOW_WORKSPACE_SELECTION_DIALOG=true
eclipse.preferences.version=1
```

Show Dialog is still ignored. The RECENT_WORKSPACES_PROTOCOL do we know/understand what the value means? Could that have any bearing on this?

**Comment by jeffmaury** [comment]
No, this is probably internal to Eclipse

**Comment by PStoner3** [comment]
Maybe I'll just uninstall and reinstall. The ultimate developer fallback.

**Comment by PStoner3** [comment]
As CodeReady Studio has reached EOL, I am closing this issue
