### ISSUE TITLE
Codereadystudio Quit Unexpectedly

### ISSUE THREAD

**Issue by ng-rh** [jbdevstudio/jbdevstudio-product#588]
Hi Team,

I installed CodeReady Studio(V: 12.21.3) using an installer in MAC OS Ventura (Version:13.0.1 ) but when I try to open the code ready studio it gets close automatically within a second.
<img width="1002" alt="Screenshot 2022-11-27 at 9 19 26 PM" src="https://user-images.githubusercontent.com/88180244/204144805-0b1e5385-9837-4bc4-8d94-0b95ff59479f.png">
[Log.txt](https://github.com/jbdevstudio/jbdevstudio-product/files/10098675/Log.txt)

**Comment by jeffmaury** [comment]
Red Hat CodeReady Studio is EOL April 2022.
See since https://developers.redhat.com/articles/2022/04/18/announcement-red-hat-codeready-studio-reaches-end-life
You should use JBoss Tools instead.

**Comment by ng-rh** [comment]
Understood, Thank you
